### ISSUE TITLE
spec_catalog.get_subtypes missing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-docutils#24]
https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/42bd1f4c6d390f004a1f0fd9b93182b384ad73bc/nwb_docutils/doctools/renderrst.py#L234

`hdmf.spec.catalog.SpecCatalog` has no method `get_subtypes`

**Comment by oruebel** [comment]
This was also added in https://github.com/hdmf-dev/hdmf/pull/13 It's in dev but we need to cut a release to get this into the HDMF on pip.
