### ISSUE TITLE
NWBNamespace.get_source_files missing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-docutils#27]
https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/1c1ac1761450b11311bbe29147fdb1525747bfcf/nwb_docutils/doctools/renderrst.py#L66

`NWBNamespace` has no method `get_source_files` and neither does `hdmf.spec.SpecNamespace`.

I think this bug can be resolved by instead using `namespace['schema']`, but then I find that `get_source_description` is also missing. This bug comes up when running `make apidoc` and `make html` and causes the following traceback:

```python
(base) Bens-MacBook-Pro-2:docs bendichter$ make apidoc
PYTHONPATH=/Users/bendichter/dev/nwbext_simulation_output/docs/source: nwb_generate_format_docs
Output directory already exists: /Users/bendichter/dev/nwbext_simulation_output/docs/source/_format_auto_docs

SORTING TYPES INTO SECTIONS
---------------------------
Traceback (most recent call last):
  File "/Users/bendichter/anaconda3/bin/nwb_generate_format_docs", line 11, in <module>
    load_entry_point('nwb-docutils', 'console_scripts', 'nwb_generate_format_docs')()
  File "/Users/bendichter/dev/nwb-docutils/nwb_docutils/generate_format_docs.py", line 473, in main
    type_sections = DataTypeSection.sort_types_to_sections(default_namespace)
  File "/Users/bendichter/dev/nwb-docutils/nwb_docutils/doctools/renderrst.py", line 67, in sort_types_to_sections
    spec_descr = namespace.get_source_description(spec_filename)
AttributeError: 'NWBNamespace' object has no attribute 'get_source_description'
make: *** [apidoc] Error 1
(base) Bens-MacBook-Pro-2:docs bendichter$ 
```

**Comment by oruebel** [comment]
The problem is that we need to cut a release for HDMF. When I updated the docutils I added and ported a number function to HDMF https://github.com/hdmf-dev/hdmf/pull/13  We need to cut releases for HDMF and the docutils. I was trying to do this on Friday but ran into troubles with the auth to get the releases certified. @ajtritt  could you cut a release of HDMF (and the docutils) until I have my auth issues resolved.
