### ISSUE TITLE
Simplify sg_prototype script using webbrowser module

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/nwb-docutils#4]
The following code could be simplified using https://docs.python.org/2.7/library/webbrowser.html

https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/467dc07916e5af56392b15c1b23f9b362bb4a7d9/nwb_docutils/sg_prototype.py#L79-L94

**Comment by nicain** [comment]
@jcfr FYI I am going to take a stab at this on the plane today.
